In [1]:
import numpy as np

In [2]:
arr_a = [1,2,3,2,3,4,3,4,5,6]
arr_b = [7,2,10,2,7,4,9,4,9,8]

In [3]:
#find matching values in two 1D array
arr_c = np.intersect1d(arr_a, arr_b)
arr_c

array([2, 4])

In [15]:
#find values in array a but not in array b
arr_d1 = np.setdiff1d(arr_a, arr_b)
arr_d1

array([1, 3, 5, 6])

In [12]:
arr_e = np.array([2,6,1,9,10,3,27,8,6,25,16])

In [14]:
#filter values in an 1D array based on conditions
arr_f = arr_e[(arr_e > 5) & (arr_e < 10)]
arr_f

array([6, 9, 8, 6])

## PYTHON NGÀY 29 THÁNG 5


In [1]:
import numpy as np
import pandas as pd 

In [38]:
#create series
ser1 = pd.Series([2,4,6,8,10])
ser2 = pd.Series([1,3,5,7,9])
print(ser1)
print(ser2)

0     2
1     4
2     6
3     8
4    10
dtype: int64
0    1
1    3
2    5
3    7
4    9
dtype: int64


In [7]:
#thuc hien cac phep toan tren Series
s = ser1+ser2
print(s)
m = ser1-ser2
print(m)
t = ser1*ser2
print(t)
t1 = ser1/ser2
print(t1)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [16]:
#kiem tra xem cac phan tu cua ser1 co lon hon cac phan tu cua ser2 ko
print(ser1[ser1 > ser2])

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [26]:
#them 2 phan tu vao ser2
ser2 = ser2.append(pd.Series([6,12]), ignore_index=True)
ser2



0     1
1     3
2     5
3     7
4     9
5     6
6    12
dtype: int64

In [28]:
#tim phan tu co trong ca hai series
ser3 = pd.Series(np.intersect1d(ser1, ser2))
ser3

0    6
dtype: int64

In [41]:
#tim phan tu chi co trong ser2 ma khong co trong ser1
ser4 = ser2[~ser2.isin(ser1)]
ser4

0    1
1    3
2    5
3    7
4    9
dtype: int64

Truy xuất các phần tử và thống kê thông tin trên series

In [53]:
#tao series ngau nhien
np.random.seed(2)
ser6 = pd.Series(np.random.randint(1,10, size = 35))
ser6

0     9
1     9
2     7
3     3
4     9
5     8
6     3
7     2
8     6
9     5
10    5
11    6
12    8
13    4
14    7
15    5
16    4
17    8
18    7
19    2
20    4
21    6
22    9
23    5
24    7
25    4
26    3
27    1
28    5
29    3
30    5
31    2
32    8
33    9
34    3
dtype: int32

In [49]:
ser6.shape

(35,)

In [50]:
ser6.head()

0    9
1    9
2    7
3    3
4    9
dtype: int32

In [51]:
ser6.tail()

30    5
31    2
32    8
33    9
34    3
dtype: int32

In [52]:
ser6 = np.array(ser6)
ser6

array([9, 9, 7, 3, 9, 8, 3, 2, 6, 5, 5, 6, 8, 4, 7, 5, 4, 8, 7, 2, 4, 6,
       9, 5, 7, 4, 3, 1, 5, 3, 5, 2, 8, 9, 3])

In [54]:
ser6.describe()

count    35.000000
mean      5.457143
std       2.392917
min       1.000000
25%       3.500000
50%       5.000000
75%       7.500000
max       9.000000
dtype: float64

In [56]:
print('tong cac phan tu trong ser6 la:',ser6.sum())
print('phan tu co tan suat xuat hien nhieu nhat trong ser6 la:', ser6.mode()[0])

tong cac phan tu trong ser6 la: 191
phan tu co tan suat xuat hien nhieu nhat trong ser6 la: 5


In [57]:
ser6[(ser6%2 == 0) & (ser6%3 == 0)]

8     6
11    6
21    6
dtype: int32

In [59]:
print(ser6[[0,5,10,15]])

0     9
5     8
10    5
15    5
dtype: int32


In [60]:
print(ser6.unique())

[9 7 3 8 2 6 5 4 1]


In [62]:
ser7 = ser6.map(lambda x: x**3)
print(ser7.head())
print(ser7.tail())

0    729
1    729
2    343
3     27
4    729
dtype: int64
30    125
31      8
32    512
33    729
34     27
dtype: int64


tạo series từ list, chuỗi và biểu thức điều kiện


In [63]:
lst = ['abc', 'defg', 'htmlj', 'dfg', 'ljsac']

In [64]:
#create series from a given list
ser_chuoi = pd.Series(lst)
ser_chuoi

0      abc
1     defg
2    htmlj
3      dfg
4    ljsac
dtype: object

In [69]:
#create a series with value is the length of each value in the given series
ser_dodai = pd.Series(len (x) for x in ser_chuoi)
ser_dodai

0    3
1    4
2    5
3    3
4    5
dtype: int64

In [76]:
ser = pd.Series(np.array([1,2,4,5,8,7,6,9]))
ser

0    1
1    2
2    4
3    5
4    8
5    7
6    6
7    9
dtype: int32

In [72]:
import math
def lasnt(n):
    if n<=1:
        return False
    elif n>1:
        for i in range (2, int(sqrt(n)+1)):
            if n%i == 0:
                return False
    return True
